namespace McProtocol.Spec

open McProtocol.Dsl

[<AutoOpen>]
module EntityMetadataValue =

    let entityMetadataValue =
        unionType "EntityMetadataValue" {
            cases (Between(766, 769)) [
                case1 0  "Byte"                [ read "value" I8 "Value" ]
                case1 1  "Int"                 [ read "value" VarInt "Value" ]
                case1 2  "Long"                [ read "value" VarLong "Value" ]
                case1 3  "Float"               [ read "value" F32 "Value" ]
                case1 4  "String"              [ read "value" Str "Value" ]
                case1 5  "Component"           [ read "value" AnonNbt "Value" ]
                case1 6  "OptionalComponent"   [ read "value" (Option AnonNbt) "Value" ]
                case1 7  "ItemStack"           [ read "value" (Named "Slot") "Value" ]
                case1 8  "Boolean"             [ read "value" Bool "Value" ]
                case1 9  "Rotations"           [ read "value" (Named "Rotations") "Value" ]
                case1 10 "BlockPos"            [ read "value" (Named "Position") "Value" ]
                case1 11 "OptionalBlockPos"    [ read "value" (Option(Named "Position")) "Value" ]
                case1 12 "Direction"           [ read "value" VarInt "Value" ]
                case1 13 "OptionalUuid"        [ read "value" (Option Uuid) "Value" ]
                case1 14 "BlockState"          [ read "value" VarInt "Value" ]
                case1 15 "OptionalBlockState"  [ read "value" VarInt "Value" ]
                case1 16 "CompoundTag"         [ read "value" AnonNbt "Value" ]
                case1 17 "Particle"            [ read "value" (Named "Particle") "Value" ]
                case1 18 "Particles"           [ read "value" (Array(Named "Particle", VarIntCount)) "Value" ]
                case1 19 "VillagerData"        [ read "value" (Named "VillagerData") "Value" ]
                case1 20 "OptionalUnsignedInt" [ read "value" VarInt "Value" ]
                case1 21 "Pose"                [ read "value" VarInt "Value" ]
                case1 22 "CatVariant"          [ read "value" VarInt "Value" ]
                case1 23 "WolfVariant"         [ read "value" (Named "RegistryWolfVariant") "Value" ]
                case1 24 "FrogVariant"         [ read "value" VarInt "Value" ]
                case1 25 "OptionalGlobalPos"   [ read "value" (Option Str) "Value" ]
                case1 26 "PaintingVariant"     [ read "value" (Named "RegistryPaintingVariant") "Value" ]
                case1 27 "SnifferState"        [ read "value" VarInt "Value" ]
                case1 28 "ArmadilloState"      [ read "value" VarInt "Value" ]
                case1 29 "Vector3"             [ read "value" (Named "Vec3f") "Value" ]
                case1 30 "Quaternion"          [ read "value" (Named "Vec4f") "Value" ]
            ]

            cases (Since 770) [
                case1 0  "Byte"                [ read "value" I8 "Value" ]
                case1 1  "Int"                 [ read "value" VarInt "Value" ]
                case1 2  "Long"                [ read "value" VarLong "Value" ]
                case1 3  "Float"               [ read "value" F32 "Value" ]
                case1 4  "String"              [ read "value" Str "Value" ]
                case1 5  "Component"           [ read "value" AnonNbt "Value" ]
                case1 6  "OptionalComponent"   [ read "value" (Option AnonNbt) "Value" ]
                case1 7  "ItemStack"           [ read "value" (Named "Slot") "Value" ]
                case1 8  "Boolean"             [ read "value" Bool "Value" ]
                case1 9  "Rotations"           [ read "value" (Named "Rotations") "Value" ]
                case1 10 "BlockPos"            [ read "value" (Named "Position") "Value" ]
                case1 11 "OptionalBlockPos"    [ read "value" (Option(Named "Position")) "Value" ]
                case1 12 "Direction"           [ read "value" VarInt "Value" ]
                case1 13 "OptionalUuid"        [ read "value" (Option Uuid) "Value" ]
                case1 14 "BlockState"          [ read "value" VarInt "Value" ]
                case1 15 "OptionalBlockState"  [ read "value" VarInt "Value" ]
                case1 16 "CompoundTag"         [ read "value" AnonNbt "Value" ]
                case1 17 "Particle"            [ read "value" (Named "Particle") "Value" ]
                case1 18 "Particles"           [ read "value" (Array(Named "Particle", VarIntCount)) "Value" ]
                case1 19 "VillagerData"        [ read "value" (Named "VillagerData") "Value" ]
                case1 20 "OptionalUnsignedInt" [ read "value" VarInt "Value" ]
                case1 21 "Pose"                [ read "value" VarInt "Value" ]
                case1 22 "CatVariant"          [ read "value" VarInt "Value" ]
                case1 23 "CowVariant"          [ read "value" VarInt "Value" ]
                case1 24 "WolfVariant"         [ read "value" VarInt "Value" ]
                case1 25 "WolfSoundVariant"    [ read "value" VarInt "Value" ]
                case1 26 "FrogVariant"         [ read "value" VarInt "Value" ]
                case1 27 "PigVariant"          [ read "value" VarInt "Value" ]
                case1 28 "ChickenVariant"      [ read "value" (Named "RegistryChickenVariant") "Value" ]
                case1 29 "OptionalGlobalPos"   [ read "value" (Option Str) "Value" ]
                case1 30 "PaintingVariant"     [ read "value" (Named "RegistryPaintingVariant") "Value" ]
                case1 31 "SnifferState"        [ read "value" VarInt "Value" ]
                case1 32 "ArmadilloState"      [ read "value" VarInt "Value" ]
                case1 33 "Vector3"             [ read "value" (Named "Vec3f") "Value" ]
                case1 34 "Quaternion"          [ read "value" (Named "Vec4f") "Value" ]
            ]
        }
